---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod
  name: httpd-multi
spec:
  containers:
    - image: bitnami/apache:2.4
      name: container1
      resources: {}
      ports:
        - containerPort: 8080
    - image: bitnami/apache:2.4
      name: container2
      resources: {}
      ports:
        - containerPort: 8081
      env:
        - name: APACHE_HTTP_PORT_NUMBER
          value: "8081"
        - name: APACHE_HTTPS_PORT_NUMBER
          value: "8444" # default being 8443
