apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-app0
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msg-label0
  template:
    metadata:
      labels:
        app: msg-label0
    spec:
      containers: 
      - name: node-bgcolor
        image: dharapvj/bgcolor-text-demo:1.0
        ports:
        - containerPort: 3000
#        env:
#        - name: MESSAGE
#          value: "Hello from the environment"
#        - name: BGCOLOR
#          value: "#d4b290"
#